title: Bloom Anti-Cheat
remote-theme: just-the-docs/just-the-docs
description: Docs to the Bloom Anti-Cheat, an anti-cheat being developed for the Roblox platform independently from the Roblox Corporation. An anti-cheat made for the people by the people in order to bring fairness and safety to the Roblox Platform.